Traceback (most recent call last):
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckeulen\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#importing the required library
import CoolProp.CoolProp as CP

#define thermodynamic variables
P_atm = 101325 #atmospheric pressure in Pa
P_it = 1.2E+6 #turbine inlet pressure in Pa 
T_it = 600 + 273.15 #turbine inlet temperatue in K
P_ot = P_atm #turbine outlet pressure in Pa
x_ot = 1#turbine outlet quality

h_it = CP.PropsSI('H', 'P', P_it, 'T', T_it, 'Water') #turbine inlet enthapy J/kg
h_ot = CP.PropsSI('H', 'P', P_ot, 'Q', x_ot, 'Water') #turbine inlet enthapy J/kg

w_t = h_it - h_ot #turbine work output per unit mass of steam in J
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 2[0m
[0;32m      1[0m [38;5;66;03m#importing the required library[39;00m
[1;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mCoolProp[39;00m[38;5;21;01m.[39;00m[38;5;21;01mCoolProp[39;00m [38;5;28;01mas[39;00m [38;5;21;01mCP[39;00m
[0;32m      4[0m [38;5;66;03m#define thermodynamic variables[39;00m
[0;32m      5[0m P_atm [38;5;241m=[39m [38;5;241m101325[39m [38;5;66;03m#atmospheric pressure in Pa[39;00m

[1;31mModuleNotFoundError[0m: No module named 'CoolProp'

