Traceback (most recent call last):
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckeulen\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import CoolProp.CoolProp as CP
import pandas as pd
import numpy as np

import plotly.graph_objs as go


fluids = ['Water', 'Ammonia', 'R134a']

for fluid in fluids:
    T_min = CP.PropsSI('Tmin', fluid) + 10  # Adding a small offset to Tmin
    T_max = CP.PropsSI('Tcrit', fluid)
    T_vals = np.linspace(T_min, T_max, 100)  # Number of points

    t_s_liquid = {'Temperature (K)': [], 'Entropy Liquid (J/kg.K)': []}
    t_s_vapor = {'Temperature (K)': [], 'Entropy Vapor (J/kg.K)': []}

    for T in T_vals:
        s_liquid = CP.PropsSI('S', 'T', T, 'Q', 0, fluid)  # Saturated liquid
        s_vapor = CP.PropsSI('S', 'T', T, 'Q', 1, fluid)  # Saturated vapor
        t_s_liquid['Temperature (K)'].append(T)
        t_s_liquid['Entropy Liquid (J/kg.K)'].append(s_liquid)
        t_s_vapor['Temperature (K)'].append(T)
        t_s_vapor['Entropy Vapor (J/kg.K)'].append(s_vapor)

    # Save to CSV
    pd.DataFrame(t_s_liquid).to_csv(f'{fluid}_T_s_liquid.csv', index=False)
    pd.DataFrame(t_s_vapor).to_csv(f'{fluid}_T_s_vapor.csv', index=False)


for fluid in fluids:
    df_liquid = pd.read_csv(f'{fluid}_T_s_liquid.csv')
    df_vapor = pd.read_csv(f'{fluid}_T_s_vapor.csv')

    # Creating Plotly plot
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=df_liquid['Entropy Liquid (J/kg.K)'], y=df_liquid['Temperature (K)'],
                             mode='lines', name='Saturated Liquid'))
    fig.add_trace(go.Scatter(x=df_vapor['Entropy Vapor (J/kg.K)'], y=df_vapor['Temperature (K)'],
                             mode='lines', name='Saturated Vapor'))

    fig.update_layout(title=f'{fluid} T-s Diagram', 
                      xaxis_title='Entropy (J/kg.K)', yaxis_title='Temperature (K)')

    # Save as HTML
    fig.write_html(f'{fluid}_T_s_plot.html')
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mCoolProp[39;00m[38;5;21;01m.[39;00m[38;5;21;01mCoolProp[39;00m [38;5;28;01mas[39;00m [38;5;21;01mCP[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m

[1;31mModuleNotFoundError[0m: No module named 'CoolProp'

