Traceback (most recent call last):
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckeulen\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ckeulen\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
## Solution:

import CoolProp.CoolProp as CP

# Given values
T = 50 + 273.15  # Temperature in Kelvin

# Approximations for compressed liquid
v = CP.PropsSI('D', 'T', T, 'Q', 0, 'Water')  # Specific volume
u = CP.PropsSI('U', 'T', T, 'Q', 0, 'Water')/1e3  # Specific internal energy
h = CP.PropsSI('H', 'T', T, 'Q', 0, 'Water')/1e3  # Specific enthalpy
s = CP.PropsSI('S', 'T', T, 'Q', 0, 'Water')/1e3  # Specific entropy

# Output the results
print(f"Specific volume: {round(v,2)} m^3/kg")
print(f"Specific internal energy: {round(u,2)} kJ/kg")
print(f"Specific enthalpy: {round(h,2)} kJ/kg")
print(f"Specific entropy: {round(s,2)} kJ/kg*K")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 3[0m
[0;32m      1[0m [38;5;66;03m## Solution:[39;00m
[1;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mCoolProp[39;00m[38;5;21;01m.[39;00m[38;5;21;01mCoolProp[39;00m [38;5;28;01mas[39;00m [38;5;21;01mCP[39;00m
[0;32m      5[0m [38;5;66;03m# Given values[39;00m
[0;32m      6[0m T [38;5;241m=[39m [38;5;241m50[39m [38;5;241m+[39m [38;5;241m273.15[39m  [38;5;66;03m# Temperature in Kelvin[39;00m

[1;31mModuleNotFoundError[0m: No module named 'CoolProp'

